export { rscBrowser } from './plugins/browser-compat/index.js'
export { rscFunctions } from './plugins/functions/index.js'
export { rscStaticPages } from './plugins/static-pages/index.js'
export type { RscStaticPagesOptions } from './plugins/static-pages/index.js'
export type { CorsOptions, FunctionsConfig, NamespaceConfig } from './types.js'
